spring:
  #\u914D\u7F6E\u6570\u636E\u6E90
  datasource:
    username: root
    password: 199661
    url: jdbc:mysql://localhost:3306/sns?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid\u6570\u636E\u6E90\u914D\u7F6E
    druid:
      # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
      initial-size: 5
      min-idle: 5
      max-active: 20
      # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      max-wait: 60000
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u6BEB\u79D2
      time-between-eviction-runs-millis: 60000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # \u6253\u5F00 PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0A PSCache \u7684\u5927\u5C0F
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684 Filter\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762 SQL \u65E0\u6CD5\u7EDF\u8BA1\uFF0Cwall \u7528\u4E8E\u9632\u706B\u5899
      filters: stat,wall
      # \u901A\u8FC7 connection-properties \u5C5E\u6027\u6253\u5F00 mergeSql \u529F\u80FD\uFF1B\u6162 SQL \u8BB0\u5F55
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # \u914D\u7F6E DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # \u914D\u7F6E DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP \u767D\u540D\u5355\uFF0C\u6CA1\u6709\u914D\u7F6E\u6216\u8005\u4E3A\u7A7A\uFF0C\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE
        allow: 127.0.0.1
        # IP \u9ED1\u540D\u5355\uFF0C\u82E5\u767D\u540D\u5355\u4E5F\u5B58\u5728\uFF0C\u5219\u4F18\u5148\u4F7F\u7528
        deny: 192.168.31.253
        # \u7981\u7528 HTML \u4E2D Reset All \u6309\u94AE
        reset-enable: false
        # \u767B\u5F55\u7528\u6237\u540D/\u5BC6\u7801
        login-username: root
        login-password: root
  messages:
    basename: normalize.login

mybatis:
  #\u6307\u5B9Amapper.xml\u4F4D\u7F6E
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.xja.springbootsns.model
  configuration:
    #\u5F00\u542F\u9A7C\u5CF0\u8F6C\u6362
    map-underscore-to-camel-case: true
    cache-enabled: true

# \u6253\u5370sql
logging:
  level:
    com.xja.springbootsns.dao: debug
